### ISSUE TITLE
Request for ability to pass headers to Post Request

### ISSUE THREAD

**Issue by gaurishchandelkar** [cleardataeng/aidews#25]
Currently while making Post request with signing, some APIs expect to receive content-type explicitly specified e.g. "content-type=application/json". 
Request to allow clients to pass Headers while making post calls. If Service object accepts a headers collection which then is added to the request by Service it will be helpful.

**Comment by satyap** [comment]
Since these exist now, can the issue be closed?

https://github.com/cleardataeng/aidews/blob/master/apigateway/aide.go#L38
https://github.com/cleardataeng/aidews/blob/master/apigateway/aide.go#L112

**Comment by gaurishchandelkar** [comment]
The functionality now exists in the library.
